server:
  port: 8300
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: web-all
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
feign:
  client:
    config:
      default:
        readTimeout: 600000
        connectTimeout: 600000